import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const basiersquare = localFont({
	src: "./fonts/basiersquare-regular-webfont.woff2",
	variable: "--font-basiersquare",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${basiersquare.variable}`}>{children}</body>
		</html>
	);
}
